### create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "testpassword@example.com",
  "password": "password1"
}

### signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "testpassword@example.com",
  "password": "password1"
}

### find user by id
GET http://localhost:3000/auth/4

### find user by email
GET http://localhost:3000/auth?email=test@example.com

### get all users
GET http://localhost:3000/auth

### delete user by id
DELETE http://localhost:3000/auth/2

### update user by id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "test123@example.com"
}